### ISSUE TITLE
flit

### ISSUE THREAD

**Issue by jaimebayes** [takluyver/bookbook#20]
Hi, 

Previous install commands run well, but when I try to run the sentence:
flit install --symlink

it throws this error:

Symlinking .\bookbook -> c:\anaconda3\Lib\site-packages\bookbook  I-flit.install
Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\flit.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\lib\site-packages\flit\__init__.py", line 188, in main
    pth=args.pth_file).install()
  File "c:\anaconda3\lib\site-packages\flit\install.py", line 407, in install
    self.install_directly()
  File "c:\anaconda3\lib\site-packages\flit\install.py", line 305, in install_directly
    os.symlink(osp.abspath(self.module.path), dst)
OSError: symbolic link privilege not held

Any advice? is it windows10 related? anaconda3-related? (flit version 2.3.0)
Thanks in advance, JL

**Comment by takluyver** [comment]
Oh yes, unfortunately that doesn't always work on Windows. If you replace `--symlink` with `--pth-file`, it will probably work.

You should always be able to `pip install bookbook`, though.

**Comment by jaimebayes** [comment]
Hi Thomas, 

Thanks, I followed your instrucctions, that error does not appear anymore.
I try to run again with some notebooks, but I got an assertion error, maybe it is caused by my source_dir, any wrong with it?:
Thanks in advance, JL

C:\github\bookbook>python -m bookbook.latex --output-file test3 **C:/github/bookbook/Capitulo/**

Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\github\bookbook\bookbook\latex.py", line 163, in <module>
    main()
  File "C:\github\bookbook\bookbook\latex.py", line 160, in main
    combine_and_convert(args.source_dir, args.output_file, args.pdf, args.template)
  File "C:\github\bookbook\bookbook\latex.py", line 144, in combine_and_convert
    combined_nb = combine_notebooks(notebook_files)
  File "C:\github\bookbook\bookbook\latex.py", line 77, in combine_notebooks
    combined_nb.cells.extend(add_sec_label(nb.cells[0], nbname))
  File "C:\github\bookbook\bookbook\latex.py", line 46, in add_sec_label
    assert cell.cell_type == 'markdown', cell.cell_type
AssertionError: code
